### ISSUE TITLE
net_asyncio Connection,....

### ISSUE THREAD

**Issue by dpineiden** [rethinkdb/rethinkdb-python#125]
Hi!

I'm using with asyncio rethinkdb and on the last version (2.4.2) i hav this problem

**Describe the bug**

```
    conn = await rc.async_connect()
  File "/home/david/Proyectos/DataDBS/datadbs/rethinkdb.py", line 72, in async_connect
    raise ex
  File "/home/david/Proyectos/DataDBS/datadbs/rethinkdb.py", line 62, in async_connect
    host=dbhost, **kwargs)
  File "/home/david/.virtualenvs/aguita37/lib/python3.7/site-packages/rethinkdb/__init__.py", line 96, in connect
    return self.make_connection(self.connection_type, *args, **kwargs)
  File "/home/david/.virtualenvs/aguita37/lib/python3.7/site-packages/rethinkdb/net.py", line 751, in make_connection
    **kwargs)
  File "/home/david/.virtualenvs/aguita37/lib/python3.7/site-packages/rethinkdb/asyncio_net/net_asyncio.py", line 333, in __init__
    super(Connection, self).__init__(ConnectionInstance, *args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:
```
I solved, in a while, with these changes:

On net_asyncio.py, line 333:
super().__init__(ConnectionInstance, *args, **kwargs)

**To Reproduce**
1. Create a new connection with await....
Using this module:
https://gitlab.com/pineiden/datadbs
Method: async_connect

**Expected behavior**
Connect like before

**System info**
 - Debian 9
 - RethinkDB Version: [2.4.0]
 - Python client version: 3.7

**Additional context**

**Comment by gabor-boros** [comment]
@dpineiden thank you for reporting this issue. I’ll check this as soon as I have time and I’ll get back to you

**Comment by dpineiden** [comment]
You welcome ;) Rethinkdb is great and i'm using this on key parts of a real time project with GPS (GNSS)

**Comment by gabor-boros** [comment]
@dpineiden Ok, I tried to look into the issue, but I'll need more context. Could you please help me with some concrete example like an `async_connect` call with `datadbs` lib? I never used it and I have no time to figure out how to use that.

So if you could give me a "hello world" which raises this issue would be more than perfect.

**Comment by dpineiden** [comment]
Hi @gabor-boros 

The system in that i'm working has two big sides:

- collector :: extract data from sources and save on rethinkdb (RDB)
https://gitlab.com/pineiden/collector/blob/master/collector/engine/engine.py
(lines 579-733)

- datawork :: obtain raw data from RDB and do some maths.
https://gitlab.com/pineiden/datawork/blob/master/datawork/gather.py
(lines 533-678)

In both cases the coro methos runs as a while-wheel

The error appeard on this part (on datawork)

```
            rc, rc_enu = self.add_sta_instance(ids, loop)
            conn = await rc.async_connect()
            rc.set_defaultdb(self.rethinkdb_dbname)
            await rc.list_dbs()
            await rc.select_db(self.rethinkdb_dbname)
            table_name = self.stations[ids]['db']  
```
The weird thing is the same call on the same py environ, didn't raise the error....

So, i hack the source code on that line on 'super()' and things works fine

**Comment by razvanavram** [comment]
I had this issue and fixed it by overriding the net_asyncio.py file.
The main difference is:

`super(Connection, self).__init__(ConnectionInstance, *args, **kwargs)`

replaced with:

`super().__init__(ConnectionInstance, *args, **kwargs)'

**Comment by gabor-boros** [comment]
Dear @razvanavram could you please help me with more info? Which python version, code example etc?

**Comment by gabor-boros** [comment]
@dpineiden It is weird. I tried to call the `async_connect` function and it worked for me. (the only thing I changed is that I dropped networktools package's prints)

```python
>>> import asyncio
>>> from rethinkdb import r
>>> from datadbs.rethinkdb import Rethink_DBS
>>> 
>>> 
>>> async def main():
...     rdbs = Rethink_DBS(dbname='test', address=('localhost', 28015))
...     connection = await rdbs.async_connect()
...     await r.table_create('marvel').run(connection)
...     marvel_heroes = r.table('marvel')
...     await marvel_heroes.insert({
...         'id': 1,
...         'name': 'Iron Man',
...         'first_appearance': 'Tales of Suspense #39'
...     }).run(connection)
...     cursor = await marvel_heroes.run(connection)
...     async for hero in cursor:
...         print(hero['name'])
... 
>>> 
>>> asyncio.get_event_loop().run_until_complete(main())
{'dbname': 'test', 'address': ('localhost', 28015)}
====CONNECTION TYPE====
<class 'rethinkdb.net_asyncio.Connection'>
test localhost 28015
<rethinkdb.RethinkDB object at 0x101526890>
Iron Man
```

Could you please check this issue in a fresh environment? I really would like to solve this issue, but right now I can not reproduce it.

**Comment by gabor-boros** [comment]
Closing the issue due to inactivity and I can not reproduce it even with the mentioned python package. Feel free to reopen it.
