### ISSUE TITLE
rethinkdb dump -- fails

### ISSUE THREAD

**Issue by 34code** [rethinkdb/rethinkdb-python#154]
**Describe the bug**
rethinkdb dump is broken

**To Reproduce**
rethinkdb dump -c db.site.com:28015 --password-file pass.txt -f backup.tar.gz

**Expected behavior**
rethinkdb dump completes successfully

**Screenshots**

**System info**
 - OS: macOS Catalina
 - rethinkdb: 2.4.0
 - Python client version: 2.4.4

**Additional context**
```NOTE: 'rethinkdb-dump' saves data, secondary indexes, and write hooks, but does *not* save
            cluster metadata.  You will need to recreate your cluster setup yourself after
            you run 'rethinkdb-restore'.
  Exporting to temporary directory...
    [                                        ]   0%
    0 rows exported from 14 tables, with 18 secondary indexes, and 0 hook functions
Unrecognized TermType: 190.
Unrecognized TermType: 190.
Unrecognized TermType: 190.
Unrecognized TermType: 190.
Unrecognized TermType: 190.
Unrecognized TermType: 190.
Unrecognized TermType: 190.
Unrecognized TermType: 190.
Unrecognized TermType: 190.
Unrecognized TermType: 190.
Unrecognized TermType: 190.
Unrecognized TermType: 190.
Unrecognized TermType: 190.
Unrecognized TermType: 190.
Errors occurred during export
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rethinkdb/_dump.py", line 169, in main
    _export.run(options)
  File "/usr/local/lib/python3.7/site-packages/rethinkdb/_export.py", line 536, in run
    run_clients(options, working_dir, db_table_set)
  File "/usr/local/lib/python3.7/site-packages/rethinkdb/_export.py", line 479, in run_clients
    raise RuntimeError("Errors occurred during export")
RuntimeError: Errors occurred during export
Error: export failed, Errors occurred during export```

**Comment by gabor-boros** [comment]
Hey @34code,

Thank you for reporting this issue! I checked Term type 190 and it seems it should be get write hook which should be known by the ast.py.

I'll check it next week!

**Comment by 34code** [comment]
thanks! In the meantime I was able to find a temp fix using an older version of the package through pip.. I think I used 2.3.0

**Comment by gabor-boros** [comment]
Hey @34code,
I checked the mentioned issue. It is weird. For me with the following parameters it works:

RethinkDB server: `rethinkdb 2.4.0-srh-special-1-28-gb2365b`
RethinkDB Python package: `2.4.4.post1`
Python: `3.7.4`

```bash
rethinkdb dump -c localhost:28015 -f /tmp/test.tar.gz --password-
file pass.txt
            NOTE: 'rethinkdb-dump' saves data, secondary indexes, and write hooks, but does *not* save
            cluster metadata.  You will need to recreate your cluster setup yourself after
            you run 'rethinkdb-restore'.
  Exporting to temporary directory...
    [========================================] 100%
    1 row exported from 1 table, with 0 secondary indexes, and 1 hook function
  Zipping export directory...
Done (0.25 seconds): /private/tmp/test.tar.gz
```

**Comment by gabor-boros** [comment]
Involving @srh to the investigation because of the C++ side of the story.

**Comment by srh** [comment]
@34code RethinkDB 2.4.0 hasn't been released.

Maybe you are actually running a 2.3.x version, with a 2.4 driver.  Then the dump command that gets shipped with it tries to call get_write_hook.

If we want the 2.4 driver's dump command to be compatible with 2.3.x servers, maybe instead the command could get the write hook off the table config.

**Comment by 34code** [comment]
I'm definitely using a 2.4 driver with a 2.3.x version. I will confirm the exact version on the server shortly. It makes sense if the driver version and the server version have to always match -- if thats the case, this is not a bug. I just confirmed I'm running 2.3.7 on the server.

**Comment by gabor-boros** [comment]
@34code The major versions must match. I mean for a 2.3.x DB a 2.3.x driver and so on. If you have no concerns I’ll close this issue, since it is working with 2.4.x DB 😊

**Comment by 34code** [comment]
thanks!
