### ISSUE TITLE
Package it as python3-rethinkdb for Debian/Ubuntu and other supported platforms.

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [rethinkdb/rethinkdb-python#165]
rethinkdb-python driver is an "official driver" and in fact it is required by `rethinkdb` for such crucial **subcommand** as `import`, so it would be great to have it packaged and make it available as `python3-rethinkdb`<sup>(\*)</sup> next to `rethinkdb` "official packages"

<sup>(\*)</sup> Debian/Ubuntu naming convention, it might be different for other distributions.

**Comment by dpineiden** [comment]
Hi Gandalf.
The rethinkdb-python module can be installed using pip. For a debian package the debian community must be check but has a lot of work, so could wait  a long time until have some published.

**Comment by gabor-boros** [comment]
I think the real solution here would be to move these kind of management commands to be part of the database and not a client.

Hence, I'm closing this issue now.
