### ISSUE TITLE
[proposal] Drop Python 2 support

### ISSUE THREAD

**Issue by gabor-boros** [rethinkdb/rethinkdb-python#168]
As of January 2020, the support Python 2 officially over. Since the code is lot more complex because of the Python 2 and 3 support, I suggest to drop Python 2 in favour of 3.

I would propose the following:
On a separate branch refactor the code to support only Python 3. Since RethinkDB 2.5.0 will introduce bigger changes (storage engine change), that would be a great opportunity to release the Python 2 version removal at that time when we release the DB itself.

**Comment by lsabi** [comment]
I completely agree with dropping python 2 support with the next big release of rethinkdb.

When you say "refactor the code to support only Python 3", do you mean to redesign the architecture of the driver or only to update the code in order to only support python 3?

**Comment by gabor-boros** [comment]
@lsabi I would do this in two steps, though it will take a bit longer. Since we can not cover the whole driver with unit and integration tests at the moment, I would feel more comfortable to do the code update first (and write the necessary tests) and after that when we can make sure we will not break things for sure, let's refactor the architecture of the driver.

**Comment by dpineiden** [comment]
+1. Python2 is deprecated now

**Comment by pgajdos** [comment]
Could you please also consider to use unittest.mock instead of mock, as a fallback at least?

**Comment by lsabi** [comment]
@pgajdos we're working on a new version of the driver, though this is not so ready yet. We're completely dropping support for python 2 and are fixing the architecture.

It's taking a while, but we're working during our spare time. We'll take your request into account

**Comment by pgajdos** [comment]
@lsabi, thanks!
