### ISSUE TITLE
Importing ABC directly from collections was deprecated and will be removed in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [rethinkdb/rethinkdb-python#186]
**Describe the bug**

Importing ABC directly from collections was deprecated and will be removed in Python 3.10 . Use collections.abc instead.

**To Reproduce**

```
rethinkdb/ast.py
87:    elif isinstance(val, collections.Callable):
108:    elif isinstance(val, collections.Mapping):
115:    elif isinstance(val, collections.Iterable):
```

**System info**
 - Python client version: 3.8

**Comment by tirkarthi** [comment]
I will raise a PR to Python 2 to 3 branch.

**Comment by gabor-boros** [comment]
Cloud gb this issue as it is resolved on the 2 to 3 branch
