### ISSUE TITLE
dump failed with v2.4.7 

### ISSUE THREAD

**Issue by Stylesoftware** [rethinkdb/rethinkdb-python#225]
**Describe the bug**
Dump errors out

**To Reproduce**
apt install python3-venv
python3 -m venv ./venv
source venv/bin/activate
pip install rethinkdb
rethinkdb dump --password

**Expected behavior**
dump file 

**Screenshots**
(venv) root@******/srv# rethinkdb dump --password
Password for `admin`:
Traceback (most recent call last):
  File "/srv/venv/bin/rethinkdb-dump", line 11, in <module>
    sys.exit(main())
  File "/srv/venv/lib/python3.6/site-packages/rethinkdb/_dump.py", line 172, in main
    options = parse_options(argv or sys.argv[1:], prog=prog)
  File "/srv/venv/lib/python3.6/site-packages/rethinkdb/_dump.py", line 109, in parse_options
    options, args = parser.parse_args(argv)
  File "/srv/venv/lib/python3.6/site-packages/rethinkdb/utils_common.py", line 432, in parse_args
    options, args = super(CommonOptionsParser, self).parse_args(*args, **kwargs)
  File "/usr/lib/python3.6/optparse.py", line 1387, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib/python3.6/optparse.py", line 1427, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/lib/python3.6/optparse.py", line 1501, in _process_long_opt
    option.process(opt, value, values, self)
  File "/usr/lib/python3.6/optparse.py", line 785, in process
    self.action, self.dest, opt, value, values, parser)
  File "/srv/venv/lib/python3.6/site-packages/rethinkdb/utils_common.py", line 311, in take_action
    values[dest] = getpass.getpass("Password for `admin`: ")
TypeError: 'Values' object does not support item assignment

**System info**
Ubuntu 18.04.5 LTS

**Comment by erSitzt** [comment]
does `--pasword-file` work for you ? i had a similar problem with a restore

**Comment by erSitzt** [comment]
a new release would be nice, as some bug are already fixed regarding dump/restore

**Comment by gabor-boros** [comment]
That's a fair point. @lsabi could you please help me checking if this error exists on master as well? If not we should definitely have a new release

**Comment by erSitzt** [comment]
Any news on this ?

**Comment by lsabi** [comment]
Nope, I didn't manage to find the root of trouble. Though, we are planning a client renewal and this feature should be moved outside clients's scope.

**Comment by besworks** [comment]
I got this to work by editing the `utils_common.py` file from the last section of the log.

```
File "/srv/venv/lib/python3.6/site-packages/rethinkdb/utils_common.py", line 311, in take_action
values[dest] = getpass.getpass("Password for admin: ")
TypeError: 'Values' object does not support item assignment
```

I changed

```
values[dest] = getpass.getpass("Password for admin: ")
```
to
```
parser.values.password = getpass.getpass("Password for `admin`: ")
```

After that I was able to enter my admin password and successfully complete a dump.

**Comment by erSitzt** [comment]
Is there ever a time when `rethinkdb-dump` just works ?
Everytime i update anythink this breaks with a new error :)

**Comment by gabor-boros** [comment]
@erSitzt Although we are planning to squash a ton of issues, PRs are always welcome.

**Comment by erSitzt** [comment]
@gabor-boros  i know :) but my python skills are not worth being called "skills" ;)
I was just a little frustrated, because i was greeted with errors on every version change of rethinkdb since we started using it in 2016 :) (only with this script i mean)
