### ISSUE TITLE
Python3.11 compatibility

### ISSUE THREAD

**Issue by stephanelsmith** [rethinkdb/rethinkdb-python#285]
Library is not compatible with Python 3.11 asyncio syntax.

Specifically, @asyncio.coroutine decorator and yield from in async are no longer allowed in 3.11.

PR here:
https://github.com/rethinkdb/rethinkdb-python/pull/284

**Comment by lsabi** [comment]
Python update for compatibility shall be added against the branch `gabor/python3-v2.5.0` that has been already started.

This branch contains already some upgraded code, but it's still a Work In Progress branch.

See

[https://github.com/rethinkdb/rethinkdb-python/tree/gabor/python3-v2.5.0](https://github.com/rethinkdb/rethinkdb-python/tree/gabor/python3-v2.5.0)

**Comment by stephanelsmith** [comment]
Rock on, thanks for the response update!

**Comment by lsabi** [comment]
I'll close this issue. Feel free to fork and PR the `gabor/python3-v2.5.0` branch
