### ISSUE TITLE
Create pypi package

### ISSUE THREAD

**Issue by gabor-boros** [rethinkdb/rethinkdb-python#30]
Create pypi package

**Comment by SunburntRock89** [comment]
How should I install the module until then?

**Comment by Randshot** [comment]
@SunburntRock89 You can use `pip install .` in the root directory.

**Comment by SunburntRock89** [comment]
This gives me an error: ![Error](https://i.da532.com/MU2m.png)

**Comment by Randshot** [comment]
Did you try running the unit-tests?

**Comment by SunburntRock89** [comment]
How do I do that?

**Comment by Randshot** [comment]
`make test-unit`

**Comment by SunburntRock89** [comment]
I get a bunch of errors importing test modules

**Comment by SunburntRock89** [comment]
Here's the bottom half of the error: ![Error](https://i.squaddy.xyz/brW9Ud.png)

**Comment by Randshot** [comment]
Can you try using Python 2.7?
I am currently installing Python 3 to test it.

**Comment by SunburntRock89** [comment]
But, can that still be used on Python 3?

**Comment by Randshot** [comment]
Ah, try this:
```
make prepare
make test-unit
```

**Comment by SunburntRock89** [comment]
holy crap you are my saviour.

**Comment by johns10** [comment]
This is a bit of a rough install.  I'm looking on the public readme.  Trying to get this in a docker machine.  Any guidance?

**Comment by gabor-boros** [comment]
CC: @grandquista 

@SunburntRock89 , @Randshot, Sorry for the late response and thank you for your help.

@johns10, We are working on integration tests with @grandquista right now to make sure that we can create a pypi package which will include a functionally working client. Theorically we got the release credentials (I have to validate it) so we will be able to release the package as rethinkdb (as it is right now).

**Comment by gabor-boros** [comment]
The packaging issue will be solved by https://github.com/rethinkdb/rethinkdb-python/pull/60.

**Comment by gabor-boros** [comment]
We got the credentials.

**Comment by gabor-boros** [comment]
Now we can create pypi packages both on test.pypi.org and pypi.org. Closing the issue.
