### ISSUE TITLE
Python 3.7+ asyncio loop type Syntax Error

### ISSUE THREAD

**Issue by mitinarseny** [rethinkdb/rethinkdb-python#68]
I have `rethinkdb==2.3.0.post6` and `Python 3.7.2`.  
When I set `r.set_loop_type('asyncio')`, I get an error:
```
File ".../rethinkdb/asyncio_net/net_asyncio.py", line 114
    asyncio.async(self.conn._parent._continue(self))
                ^
SyntaxError: invalid syntax
```
Fix this, please.

**Comment by pashazz** [comment]
Fixed in v 2.4.0

**Comment by mitinarseny** [comment]
Could you kindly update [rethinkdb](https://pypi.org/project/rethinkdb/) package on [PyPi](https://pypi.org/) to `v2.4.0`?

**Comment by pashazz** [comment]
@mitinarseny 
Unfortunately I'm not a developer of this library

**Comment by pashazz** [comment]
Although it's not _precisely_ written you can clone this repository, then eecute the following  from rethinkdb-python dir:
```
make prepare
pip install .
```

**Comment by gabor-boros** [comment]
Currently the pypi credentials are missing (after the takeover, we did not got the credentials, so I have to solve it next week)

**Comment by gabor-boros** [comment]
The packaging issue will be solved by https://github.com/rethinkdb/rethinkdb-python/pull/60.

**Comment by gabor-boros** [comment]
PyPi package is on its way.

**Comment by mitinarseny** [comment]
> The packaging issue will be solved by #60.

Well, when?)

**Comment by bdschr** [comment]
+1 for package update on pypi. Not being able to install it with git+ is annoying and requires additional steps in my CI pipeline.

**Comment by SirEdvin** [comment]
@gabor-boros hey, what with package upload? I read, that pypi team assign the project to you.

**Comment by gabor-boros** [comment]
Yep, I'll do the upload this weekend. I had a really hard month.

**Comment by gabor-boros** [comment]
@SirEdvin, @bdschr, @mitinarseny, @pashazz this issue will be resolved by https://github.com/rethinkdb/rethinkdb-python/pull/91

**Comment by gabor-boros** [comment]
FYI: The package has been deployed.
[![PyPI version](https://badge.fury.io/py/rethinkdb.svg)](https://badge.fury.io/py/rethinkdb)
