### ISSUE TITLE
Generate proto files on git install

### ISSUE THREAD

**Issue by tommilligan** [rethinkdb/rethinkdb-python#76]
Currently, protocol buffer files are not generated during a git install. They require a separate `make prepare` step, which means we can't use a git reference with tools like `pip` or `pipenv`. This leads to errors like:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tom/reinfer/rethinkdb-python/rethinkdb/ast.py", line 28, in <module>
    from rethinkdb import ql2_pb2
ImportError: cannot import name 'ql2_pb2' from 'rethinkdb' (/home/tom/reinfer/rethinkdb-python/rethinkdb/__init__.py)
```

It's possible to run external commands like `make` during the install process, see [this SO question](https://stackoverflow.com/questions/45347685/run-makefile-on-pip-install). It should also be possible to only run these steps if the protocol buffer files are not already present (i.e. during a git install, not in a PyPI install).

This isn't something I've done before, but happy to give it a go if others are open to the idea?

**Comment by gabor-boros** [comment]
I can see your point. What is the reason behind the editable install? Just asking because if the package release delay, I can make sure that a new package version will be deployed this week to pypi (we got credentials)

**Comment by tommilligan** [comment]
It was initially because of the package install, but now I'm looking around at other similar packages and they do just say _"Install it with these steps"_, and use a Makefile (which we're currently doing). I'll see if I can find an example in a well used package, otherwise I'll close this

**Comment by gabor-boros** [comment]
@tommilligan have you found any examples?

**Comment by tommilligan** [comment]
Haven't looked into it and is no longer an issue for me - closing
