### ISSUE TITLE
Show stopping bugs in `rethinkdb.logger`

### ISSUE THREAD

**Issue by mehaase** [rethinkdb/rethinkdb-python#79]
There are a few show stopping bugs in `rethinkdb.logger`.

The first issue is that the call to `logging.basicConfig()` is incorrect. The `format` argument should be a `str`, not a `logging.Formatter`. This causes all logging calls to produce the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 620, in format
    if self.usesTime():
  File "/usr/lib/python3.7/logging/__init__.py", line 588, in usesTime
    return self._style.usesTime()
  File "/usr/lib/python3.7/logging/__init__.py", line 430, in usesTime
    return self._fmt.find(self.asctime_search) >= 0
AttributeError: 'Formatter' object has no attribute 'find'
```

The corrected code should be:

```python
        log_format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        logging.basicConfig(format=log_format)
```

The second issue is that a library module should never call `logging.basicConfig()` because it reconfigures global logging and affects all other modules. For example, in an application I am developing, I have logging calls throughout the code. As soon as I `import rethinkdb` my own code is no longer able to do any logging due to the bug above. As an application developer, I don't want a module to change the way my application does its logging.

Finally, I'm not sure what the purpose of this `DriverLogger` class is. It has some weird features for exception handling and "write to console", but these all seem like operations only used for debugging that could be handled using Python's native logging instead.

I am happy to write up a PR to fix any or all of these issues, but will wait for feedback on this issue before doing so. Please let me know what you think.

**Comment by mehaase** [comment]
The first issue is resolve in this commit (now on master): https://github.com/rethinkdb/rethinkdb-python/commit/96b991c6d0a78f9f68de33522232293c2a93d866

But the second and third issues are not resolved. What do you think @gabor-boros @grandquista?

**Comment by grandquista** [comment]
I will look at removing the call for the second issue. The third is a symptom of trying to get a handle on how exceptions were used internally. When we started this refactor there were a number of places that swallowed all exceptions. Or simply caught a re raised. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by grandquista** [comment]
The second issue is solved. At the same time I namespaced our logger to help moving forward. For the third I think we want to ensure all our logging is done at the `DEBUG` level. I'm basing this on Django where turning up to that level gets me all the Postgres events. Write to console is mostly for ease of testing. It could be replaced with a good set of mock utilities.

**Comment by mehaase** [comment]
Thanks @grandquista for working on the second issue!

> For the third I think we want to ensure all our logging is done at the DEBUG level.

Agreed.

> Write to console is mostly for ease of testing. It could be replaced with a good set of mock utilities.

Can you explain this a bit more? Pytest will automatically display log messages for all failing test cases. Here's an example:

```python
import logging

logger = logging.getLogger()

def test_always_passes():
    logger.debug('this test always passes')
    assert True

def test_always_fails():
    logger.debug('this test always fails')
    assert False
```

Pytest can be configured to display debug logs:

```
> pytest test_foo.py --log-level debug
============================ test session starts ============================
platform linux -- Python 3.6.7, pytest-4.2.0, py-1.8.0, pluggy-0.9.0
rootdir: /home/mhaase/code/hyperiongray/rethinkdb-python, inifile: setup.cfg
plugins: cov-2.6.1
collected 2 items                                                                                                         

test_foo.py .F                                                         [100%]

================================= FAILURES ==================================
_____________________________ test_always_fails _____________________________

    def test_always_fails():
        logger.debug('this test always fails')
>       assert False
E       assert False

test_foo.py:11: AssertionError
----------------------------- Captured log call -----------------------------
test_foo.py                 10 DEBUG    this test always fails
===================== 1 failed, 1 passed in 0.03 seconds ====================
```

Or did I misunderstand the comment about testing?

**Comment by grandquista** [comment]
> Can you explain this a bit more?

As you mentioned, only for failing cases. Sometimes output from successful tests was important.

It is mostly an internal duplication of `tee`, and was helpful during large scale refactoring.

**Comment by gabor-boros** [comment]
@grandquista @mehaase Can we close this issue?
