### ISSUE TITLE
Create proper travis ci config

### ISSUE THREAD

**Issue by gabor-boros** [rethinkdb/rethinkdb-python#80]
The current Travis CI setup is a mess (sorry for that by the way). We need to figure out how to do it better.

A partially related issue is that we can not run integration tests on forks because of encrypted env variables. Potentially we could turn them off for PRs. What do you think @grandquista?

**Comment by grandquista** [comment]
Travis is pretty good about explaining why it is running, so it makes disabling on certain runs easy.
