### ISSUE TITLE
Asyncio support: 'TypeError: 'async for' received an object from __aiter__ that does not implement __anext__: generator'

### ISSUE THREAD

**Issue by MichalMazurek** [rethinkdb/rethinkdb-python#92]
Cannot use cursor with `async for`.

## Expected Behavior

```
cursor = await marvel_heroes.run(connection)
    async for hero in cursor:
        print(hero['name'])
```

## Current Behavior

```
cursor = await marvel_heroes.run(connection)
    async for hero in cursor:
        print(hero['name'])

TypeError: 'async for' received an object from `__aiter__` that does not implement __anext__: generator
```

## Possible Solution

Remove @asyncio.coroutine decorator from `__aiter__` method of AsyncioCursor on line 95 in net_asyncio.py

## Steps to Reproduce

Given above.

## Context (Environment)

Python 3.7.2, you can't use cursors in `async for`

**Comment by grandquista** [comment]
I'm having trouble squaring the problem with the original [code](https://github.com/rethinkdb/rethinkdb/commit/dda2fea6326182350c7e845378efc6749c49ec13). Is this a 3.7 only problem? I can write some tests now that we are running 3.7 in the suite.

**Comment by MichalMazurek** [comment]
It might be 3.7 specific, I didn't have much time to test it on 3.6, sorry.

**Comment by MichalMazurek** [comment]
Anyhow, in this pep https://www.python.org/dev/peps/pep-0525/ there as an example for an asynchronous generator. The `__aiter__` is not a coroutine. And it was implemented in 2016 with 3.6 https://bugs.python.org/issue28003. It might be the same issue on 3.6 as well.

**Comment by gabor-boros** [comment]
Linking the related PR https://github.com/rethinkdb/rethinkdb-python/pull/93

**Comment by gabor-boros** [comment]
PR is on the master. I’ll close he issue when we release the new version

**Comment by gabor-boros** [comment]
one of the two release blockers is merged

**Comment by gabor-boros** [comment]
@MichalMazurek v2.4.1 released (by accident, but) except the trio integration it should work properly now. Could you please try it out?

**Comment by MichalMazurek** [comment]
I wil do it today :)

**Comment by MichalMazurek** [comment]
Sorry, had some problems with connectivity yesterday. I can confirm that it works properly :)

**Comment by gabor-boros** [comment]
@MichalMazurek No problems and thank you for the confirmation! I’m closing this issue then. We have an issue with the trio integration but it is an other topic.
