### ISSUE TITLE
Can keep old import ways `import rethinkdb as r`  in 2.4.0?

### ISSUE THREAD

**Issue by codeskyblue** [rethinkdb/rethinkdb-python#96]
Since lot of code is build with 2.3.6.post6, Is there any simple way to upgrade to 2.4.0?

**Comment by gabor-boros** [comment]
@codeskyblue Hi! ✋ 
The short answer is that we dropped this import format, due to we faced with lot of circular imports and other issues as well in the `__init__.py`, so we would not like to keep the old import style. (@grandquista if you have other opinion, please raise your hand)

**Comment by grandquista** [comment]
Do a replacement with `import rethinkdb as r; r = r. RethinkDB()` would be the upgrade path

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codeskyblue** [comment]
@gabor-boros How about add code `r = RethinkDB()` at the end of `__init__.py`, so we can use

`from rethinkdb import r` instead of `import rethinkdb as r`

**Comment by gabor-boros** [comment]
As I remember it leads to an issue but I’ll check it this weekend. If it is possible I’ll open a PR for this.

**Comment by celogeek** [comment]
Well, I think the right import syntax is:
```
from rethinkdb import RethinkDB as r
```

**Comment by auyer** [comment]
`from rethinkdb import RethinkDB as r ` alone does not work because you need to initialize the class.

**Comment by gabor-boros** [comment]
@celogeek, @codeskyblue, @grandquista The best what I can do to mitigate this is what @codeskyblue suggested (`from rethinkdb import r`). If it is ok for you I can open a PR with the changes.

**Comment by gabor-boros** [comment]
Due to #102 is merged, I'm closing this issue. Feel free to ask for reopen if you think it is not ok.
