### ISSUE TITLE
[BUG] .do() methods are not working as expected

### ISSUE THREAD

**Issue by auyer** [rethinkdb/rethinkdb-python#99]
Back in  2.3.0 I tested this the `.do()`, and it still doesn't work i 2.4.

```
r.db_list().contains(DATABASE).do(r.branch(True,{ 'dbs_created': 0 },r.db_create(DATABASE))).run(connection)
```
## Expected Behavior

It is expected that the `.do()` would execute the lamda functions and `r.branch()` functions

## Current Behavior

The `.do()` function does not execute correctly

## Steps to Reproduce

1. Open the Python interpreter
2. run the following piece of code:
```
from rethinkdb import RethinkDB
r = RethinkDB()
connection = r.connect(host="10.30.0.94", port=28015)
r.db_list().contains("non_existant_db").do(r.branch(
        True,
        { 'dbs_created': 0 },
        r.db_create("non_existant_db")
    )).run(connection)
```
3. It will produce `{'dbs_created': 0}` for every database name

## Context (Environment)
Python version: 3.7.2
Driver Version: 2.4.1
Server Version: rethinkdb 2.3.6~0jessie (GCC 4.9.2)

In a application, I needed to use `.do()` to watch a `.changes()` routine. Not being able to use `.do()` requires me to create a loop ( and this breaks the rest of my code).  It also makes some code bigger than needed.

Another Secptum user reported using a similar query, achieving the following results:
```
r.db_list().do(lambda result: print(result.__dict__)).run(connection)
> {'_args': [<RqlQuery instance: 4 >], 'optargs': {}}
```

**Comment by gabor-boros** [comment]
Hello @auyer we will need some time to investigate. Could you please share some detail about your setup? For example python version, RethinkDB (server and python client) versions?

**Comment by gabor-boros** [comment]
@auyer thank you, I’ll try to investigate this issue in the upcoming days if @grandquista is not faster than me 😏

**Comment by grandquista** [comment]
It probably needs more research, but the first clue I see is there is no `r.row` in that lambda

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gabor-boros** [comment]
Ok, so maybe I misunderstood something, but what I got is: "If there is no db, then create it".

If this is the case, then you are missing a lambda function there. So you could write the following:
```python
from rethinkdb import RethinkDB

r = RethinkDB()
connection = r.connect()

# Note the "lambda exists:" part
r.db_list().contains('non_existant_db').do(
  lambda exists: r.branch(exists, {'dbs_created': 0}, r.db_create('non_existant_db'))
).run(connection)
```

Due to this is working, I'm closing this issue. If you feel that this does not solves your problem, feel free to comment here and I'll reopen this.

**Comment by grandquista** [comment]
The original should still work. I’m guessing the bug is we lost a force coerce argument to function since its missing the meta operation. The original isn’t dynamic, and that shouldn’t be part of the bug

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
